apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-teszt"
  annotations:
    backstage.io/techdocs-ref: dir:.
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
  links:
    - url: https://localhost:3001
      title: Basic react app
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
