apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-teszt"
  links:
    - url: https://google.com
      title: Google
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
